### PR TITLE
Added AUR package to README

### PR DESCRIPTION
**Pull request by lewisdoesstuff**
Package seems well maintained

### CODE REVIEW

**Comment by TricksterGuy** [comment]
lol now that we've met in person and had a vague conversation about this.

I'm hesitant to merge this because I have not seen the application running on Arch.  I would ideally like for people who make these sorts of utilities to support it and become the maintainer for that distro.

My goal is to have the GUI's look and feel / behavior be consistent on all platforms.  The application's tests don't cover most of the code so again uneasy about accepting this.

The whole mention of me revisiting this in December is that is when I will have time to have more rigorous automated tests for the application.  If at that point when I have more tests and more confidence  that the application works then I will merge this request.

**Comment by DeathByKorea** [comment]
You might be thinking of the wrong guy here, Haven't met you aha
Not on Arch anymore due to some annoying issues with drivers, but if I'm back on Arch by then I'd be happy to help maintain the package

**Comment by TricksterGuy** [comment]
GAH! I'm totally confused, I just talked with someone in person who did say they were running arch and submitted a pull request here.

Well anyway, yeah the main users of this program will use Ubuntu or Ubuntu-like systems.  Yeah I am trying to expand this to other distros and OSes, but not enough automated tests to verify confidence there.

**Comment by acxz** [comment]
I believe adding the latest upstream version of complx (complx-git) is a bad idea to the wiki. If anything the release version should be added, [complx](https://aur.archlinux.org/packages/complx/). This PR should be closed.

**Pull request closed without merging**
