### PR TITLE
Create PKGBUILD for Arch

### PR DESCRIPTION
**Pull request by sduddikunta**
Arch package can be created by copying this file's contents into a file named PKGBUILD in an empty directory and running makepkg from that directory.

### CODE REVIEW

**Comment by TricksterGuy** [comment]
Ok I'm reading up on PKGBUILD files I will comment once I know what this is doing.

**Comment by sduddikunta** [comment]
I modified the PKGBUILD so it doesn't redownload the source. Packages can be generated just by running "makepkg" at the root of the cloned git tree.

**Comment by khayyamsaleem** [comment]
This one works:

pkgname=complx-git
pkgver=4.13.1.18.g8284223
pkgrel=1
pkgdesc="Complx the LC-3 Simulator used in CS2110 managed by Brandon"
arch=('i686' 'x86_64')
url="https://www.github.com/TricksterGuy/complx"
license=('unknown')
depends=('wxgtk')
makedepends=('git' 'webkitgtk2')
provides=('complx')
conflicts=('complx')
source=("${pkgname}::git+${url}")
md5sums=('SKIP')

pkgver() {
  cd "$srcdir/$pkgname"
  git describe --long --tags | sed 's/-/./g'
}

build() {
  cd "$srcdir/$pkgname"
  mkdir -p build && cd build
  cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  make
}

package() {
  cd "$srcdir/$pkgname"
  cd build
  make DESTDIR="${pkgdir}" install
}

# vim:set ts=2 sw=2 et:

**Comment by khayyamsaleem** [comment]
pardon, idk markdown

pkgname=complx-git
pkgver=4.13.1.18.g8284223
pkgrel=1
pkgdesc="Complx the LC-3 Simulator used in CS2110 managed by Brandon"
arch=('i686' 'x86_64')
url="https://www.github.com/TricksterGuy/complx"
license=('unknown')
depends=('wxgtk')
makedepends=('git' 'webkitgtk2')
provides=('complx')
conflicts=('complx')
source=("${pkgname}::git+${url}")
md5sums=('SKIP')

pkgver() {
  cd "$srcdir/$pkgname"
  git describe --long --tags | sed 's/-/./g'
}

build() {
  cd "$srcdir/$pkgname"
  mkdir -p build && cd build
  cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  make
}

package() {
  cd "$srcdir/$pkgname"
  cd build
  make DESTDIR="${pkgdir}" install
}

**Comment by TricksterGuy** [comment]
hmm alright not an arch linux user here  so whats the purpose of these PKGBUILD files?

also I should note that someone put it in AUR about a year ago. https://aur.archlinux.org/packages/complx-git/

would this still be needed if its in AUR?

**Comment by khayyamsaleem** [comment]
they put it in the aur but it doesn't work. 
pkgbuild files are basically just the sequence of operations required to build a package. the existing package on the aur has a pkgbuild file but it's wrong and it doesn't build.

**Comment by khayyamsaleem** [comment]
though i guess the guy who put it on the AUR would have to be the guy to update the pkgbuild

**Comment by acxz** [comment]
Any AUR discussions on the [`complx`](https://aur.archlinux.org/packages/complx/) or [`complx-git`](https://aur.archlinux.org/packages/complx-git/) packages should happen on the comments thread of the respective package. I do not believe this is the place to discuss AUR PKGBUILDs. This pull request should be closed.

**Pull request closed without merging**
